server:
  port: 8080
spring:
  application:
    name: auth-management
  datasource:
    url: jdbc:mysql://localhost:3306/main_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: P@ssw0rd
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
#  main:
#    allow-circular-references: true
#  cloud:
#    compatibility-verifier:
#      enabled: false